### ISSUE TITLE
Bug - Feature - To find Status of booking

### ISSUE THREAD

**Issue by selvianu** [csys-fresher-batch-2021/trainticketbooking-core#2]
Scenario: As a user, I should be able to view the status of my booking
Bug: The method doesn't give the status for the given booking_id.

![image](https://user-images.githubusercontent.com/22638364/126177497-18752275-5d5e-4de3-8950-62bd9c5cb535.png)

**Comment by sakilvenkat** [comment]
I changed id into name to display status about train
