### ISSUE TITLE
Bug - Feature - No validator

### ISSUE THREAD

**Issue by selvianu** [csys-fresher-batch-2021/trainticketbooking-core#3]
Scenario: When a user needs to check the status of the booked tickets, it should be a valid data to check the status.
Bug : The method written takes a invalid booking id for checking the status. Only the valid booking id should be able to check the booing status.

![image](https://user-images.githubusercontent.com/22638364/126180534-d93cc6c6-9d91-44d2-a01c-1bca40623fff.png)

**Comment by sakilvenkat** [comment]
Fixed Validator bug issue
